plugins {
    id 'java-library'
}

group = 'com.jrl.ai'
version = '0.1.0-SNAPSHOT'

subprojects {
    apply plugin: 'java-library'

    group = 'com.jrl.ai'
    version = rootProject.version

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    javadoc {
        options.addBooleanOption('Xdoclint:none', true)
        failOnError = false
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        // Logging
        implementation 'org.slf4j:slf4j-api:2.0.13'

        // Testing
        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs.addAll(['-parameters'])
    }
}
